# <--------------> load data script params
local_dir: "./Data"
split_tt: 0.9
split_tv: 0.8
seed: 42
# <-------------->

# hyperparameters
batch_size: 64
num_workers: 4
learning_rate: 0.0001
epochs: 10
weight_decay: 0.001